<script type="text/javascript">
    var validator = {

        formValidator :function(){
            var d = document;
            var isValid = false;
            
            
            //checking that the required fields are not empty.
            if((d.getElementById('email_id').value != '') 
                && (d.getElementById('password').value != '')) {
                //checking that the email_id is indeed a email_id
                if(!validator.isEmailId(d.getElementById('email_id').value)) {
                    alert('Invalid Email ID');
                    isValid = false;
                }
                else
                    isValid = true;
            }
            else {
                alert("Please Fill all the fields.");
                isValid = false;
            }
            if(isValid == true) {
                d.getElementById('form1').submit();
            }
        },
        
        isEmailId : function(str){
                if(str == null)
                {
                    //alert("Please enter valid emailId");
                    return false;
                }
                str = this.trim(str);
                if(str.search(/\s/) != -1)
                {
                    //alert("Please enter a valid emaiId");
                    return false;
                }
                var p_email = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
                var matches = str.match(p_email);
                if(matches == null || matches[0] != str)
                {
                    //alert("Please enter a valid emaiId");
                    return false;
                }
                
                
                return true;
                
        },
        
        trim: function(str) {
            str = str.replace(/\s+/g," ");
            str = str.replace(/^\s|\s$/g,"");
            return str;
        }
        
    };
</script>
<div id="page">
    <div>

      <h3><big style = "margin-left:405px">Sign in</big></h3>

      <div class="sideMenu">
        <form id="form1" method="post" action="/login/sign-in">
          <table width="100%" border="0" align="center" cellpadding="5" cellspacing="0">
              <?php if(isset($this->errorMsg)):?>
                  <tr align="center">
                    <td style = "font-color:red"><?php echo $this->errorMsg;?> </td>
                  </tr>
              <?php endif;?>
              <tr align="center">
                <td>Email Id : </td>
              </tr>
              <tr align="center">
                <td><input type="text" name="email_id" id="email_id" value = '<?php echo $this->emailId;?>'/></td>
              </tr>
              <tr align="center">
                <td>Password:</td>
              </tr>
              <tr align="center">
                <td><input type="password" name="password" id="password"/></td>
              </tr>
              <tr align="center">
                <td><input name="Submit" type="button" value="Submit" onclick = "validator.formValidator();"/></td>
              </tr>
            </table>
        </form>
      </div>
            



    </div>