<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Smail App</title>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 80px;">
    <div id="header-logo" style="float: left">
        <h1>Welcome to SMAIL </h1>
    </div>
</div>
<?php echo $this->layout()->content; ?>
<div id="footer" style="background-color: #EEEEEE; height: 60px;">
</div>

</body>
</html>